//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentReportCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int StudentDetailId { get; set; }
        public int StudentId { get; set; }
        public int SubjectId { get; set; }
        public decimal MarksObtained { get; set; }
        public decimal TotalMarks { get; set; }
        public decimal Percentage { get; set; }
    }
}
